// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: dormitoryService.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dormitory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	BuildingID  string `protobuf:"bytes,2,opt,name=BuildingID,proto3" json:"BuildingID,omitempty"`
	Floor       uint32 `protobuf:"varint,3,opt,name=Floor,proto3" json:"Floor,omitempty"`
	LivedNumber uint32 `protobuf:"varint,4,opt,name=LivedNumber,proto3" json:"LivedNumber,omitempty"`
	MaxNumber   uint32 `protobuf:"varint,5,opt,name=MaxNumber,proto3" json:"MaxNumber,omitempty"`
	Sn          string `protobuf:"bytes,6,opt,name=Sn,proto3" json:"Sn,omitempty"`
}

func (x *Dormitory) Reset() {
	*x = Dormitory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dormitory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dormitory) ProtoMessage() {}

func (x *Dormitory) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dormitory.ProtoReflect.Descriptor instead.
func (*Dormitory) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{0}
}

func (x *Dormitory) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Dormitory) GetBuildingID() string {
	if x != nil {
		return x.BuildingID
	}
	return ""
}

func (x *Dormitory) GetFloor() uint32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *Dormitory) GetLivedNumber() uint32 {
	if x != nil {
		return x.LivedNumber
	}
	return 0
}

func (x *Dormitory) GetMaxNumber() uint32 {
	if x != nil {
		return x.MaxNumber
	}
	return 0
}

func (x *Dormitory) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type GetDormitoryListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn string `protobuf:"bytes,1,opt,name=Sn,proto3" json:"Sn,omitempty"`
}

func (x *GetDormitoryListRequest) Reset() {
	*x = GetDormitoryListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDormitoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDormitoryListRequest) ProtoMessage() {}

func (x *GetDormitoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDormitoryListRequest.ProtoReflect.Descriptor instead.
func (*GetDormitoryListRequest) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{1}
}

func (x *GetDormitoryListRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type GetDormitoryListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DormitoryList []*Dormitory `protobuf:"bytes,1,rep,name=DormitoryList,proto3" json:"DormitoryList,omitempty"`
	Code          string       `protobuf:"bytes,100,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg           string       `protobuf:"bytes,101,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *GetDormitoryListResponse) Reset() {
	*x = GetDormitoryListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDormitoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDormitoryListResponse) ProtoMessage() {}

func (x *GetDormitoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDormitoryListResponse.ProtoReflect.Descriptor instead.
func (*GetDormitoryListResponse) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{2}
}

func (x *GetDormitoryListResponse) GetDormitoryList() []*Dormitory {
	if x != nil {
		return x.DormitoryList
	}
	return nil
}

func (x *GetDormitoryListResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetDormitoryListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateDormitoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dormitory *Dormitory `protobuf:"bytes,1,opt,name=Dormitory,proto3" json:"Dormitory,omitempty"`
}

func (x *CreateDormitoryRequest) Reset() {
	*x = CreateDormitoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDormitoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDormitoryRequest) ProtoMessage() {}

func (x *CreateDormitoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDormitoryRequest.ProtoReflect.Descriptor instead.
func (*CreateDormitoryRequest) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDormitoryRequest) GetDormitory() *Dormitory {
	if x != nil {
		return x.Dormitory
	}
	return nil
}

type CreateDormitoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Code string `protobuf:"bytes,100,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,101,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *CreateDormitoryResponse) Reset() {
	*x = CreateDormitoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDormitoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDormitoryResponse) ProtoMessage() {}

func (x *CreateDormitoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDormitoryResponse.ProtoReflect.Descriptor instead.
func (*CreateDormitoryResponse) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDormitoryResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateDormitoryResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateDormitoryResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateDormitoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dormitory *Dormitory `protobuf:"bytes,1,opt,name=Dormitory,proto3" json:"Dormitory,omitempty"`
}

func (x *UpdateDormitoryRequest) Reset() {
	*x = UpdateDormitoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDormitoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDormitoryRequest) ProtoMessage() {}

func (x *UpdateDormitoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDormitoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateDormitoryRequest) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDormitoryRequest) GetDormitory() *Dormitory {
	if x != nil {
		return x.Dormitory
	}
	return nil
}

type UpdateDormitoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,100,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,101,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *UpdateDormitoryResponse) Reset() {
	*x = UpdateDormitoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDormitoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDormitoryResponse) ProtoMessage() {}

func (x *UpdateDormitoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDormitoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateDormitoryResponse) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDormitoryResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateDormitoryResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteDormitoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteDormitoryRequest) Reset() {
	*x = DeleteDormitoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDormitoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDormitoryRequest) ProtoMessage() {}

func (x *DeleteDormitoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDormitoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteDormitoryRequest) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDormitoryRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteDormitoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,100,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,101,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *DeleteDormitoryResponse) Reset() {
	*x = DeleteDormitoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDormitoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDormitoryResponse) ProtoMessage() {}

func (x *DeleteDormitoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDormitoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteDormitoryResponse) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDormitoryResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeleteDormitoryResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Building struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DmID     string `protobuf:"bytes,2,opt,name=DmID,proto3" json:"DmID,omitempty"`
	Location string `protobuf:"bytes,3,opt,name=Location,proto3" json:"Location,omitempty"`
	Name     string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Building) Reset() {
	*x = Building{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Building) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Building) ProtoMessage() {}

func (x *Building) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Building.ProtoReflect.Descriptor instead.
func (*Building) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{9}
}

func (x *Building) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Building) GetDmID() string {
	if x != nil {
		return x.DmID
	}
	return ""
}

func (x *Building) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Building) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBuildingListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetBuildingListRequest) Reset() {
	*x = GetBuildingListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBuildingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildingListRequest) ProtoMessage() {}

func (x *GetBuildingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildingListRequest.ProtoReflect.Descriptor instead.
func (*GetBuildingListRequest) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{10}
}

func (x *GetBuildingListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBuildingListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildingList []*Building `protobuf:"bytes,1,rep,name=BuildingList,proto3" json:"BuildingList,omitempty"`
	Code         string      `protobuf:"bytes,100,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg          string      `protobuf:"bytes,101,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *GetBuildingListResponse) Reset() {
	*x = GetBuildingListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBuildingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildingListResponse) ProtoMessage() {}

func (x *GetBuildingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildingListResponse.ProtoReflect.Descriptor instead.
func (*GetBuildingListResponse) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{11}
}

func (x *GetBuildingListResponse) GetBuildingList() []*Building {
	if x != nil {
		return x.BuildingList
	}
	return nil
}

func (x *GetBuildingListResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetBuildingListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateBuildingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Building *Building `protobuf:"bytes,1,opt,name=Building,proto3" json:"Building,omitempty"`
}

func (x *CreateBuildingRequest) Reset() {
	*x = CreateBuildingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBuildingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildingRequest) ProtoMessage() {}

func (x *CreateBuildingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildingRequest.ProtoReflect.Descriptor instead.
func (*CreateBuildingRequest) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{12}
}

func (x *CreateBuildingRequest) GetBuilding() *Building {
	if x != nil {
		return x.Building
	}
	return nil
}

type CreateBuildingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Code string `protobuf:"bytes,100,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,101,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *CreateBuildingResponse) Reset() {
	*x = CreateBuildingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBuildingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildingResponse) ProtoMessage() {}

func (x *CreateBuildingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildingResponse.ProtoReflect.Descriptor instead.
func (*CreateBuildingResponse) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{13}
}

func (x *CreateBuildingResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateBuildingResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateBuildingResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateBuildingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Building *Building `protobuf:"bytes,1,opt,name=Building,proto3" json:"Building,omitempty"`
}

func (x *UpdateBuildingRequest) Reset() {
	*x = UpdateBuildingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBuildingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBuildingRequest) ProtoMessage() {}

func (x *UpdateBuildingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBuildingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBuildingRequest) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateBuildingRequest) GetBuilding() *Building {
	if x != nil {
		return x.Building
	}
	return nil
}

type UpdateBuildingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,100,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,101,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *UpdateBuildingResponse) Reset() {
	*x = UpdateBuildingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBuildingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBuildingResponse) ProtoMessage() {}

func (x *UpdateBuildingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBuildingResponse.ProtoReflect.Descriptor instead.
func (*UpdateBuildingResponse) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateBuildingResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateBuildingResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteBuildingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteBuildingRequest) Reset() {
	*x = DeleteBuildingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBuildingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildingRequest) ProtoMessage() {}

func (x *DeleteBuildingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildingRequest.ProtoReflect.Descriptor instead.
func (*DeleteBuildingRequest) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteBuildingRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteBuildingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,100,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,101,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *DeleteBuildingResponse) Reset() {
	*x = DeleteBuildingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBuildingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildingResponse) ProtoMessage() {}

func (x *DeleteBuildingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildingResponse.ProtoReflect.Descriptor instead.
func (*DeleteBuildingResponse) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteBuildingResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeleteBuildingResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Live struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DormitoryID string `protobuf:"bytes,2,opt,name=DormitoryID,proto3" json:"DormitoryID,omitempty"`
	StudentID   string `protobuf:"bytes,3,opt,name=StudentID,proto3" json:"StudentID,omitempty"`
	LiveDate    string `protobuf:"bytes,4,opt,name=LiveDate,proto3" json:"LiveDate,omitempty"`
}

func (x *Live) Reset() {
	*x = Live{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Live) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Live) ProtoMessage() {}

func (x *Live) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Live.ProtoReflect.Descriptor instead.
func (*Live) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{18}
}

func (x *Live) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Live) GetDormitoryID() string {
	if x != nil {
		return x.DormitoryID
	}
	return ""
}

func (x *Live) GetStudentID() string {
	if x != nil {
		return x.StudentID
	}
	return ""
}

func (x *Live) GetLiveDate() string {
	if x != nil {
		return x.LiveDate
	}
	return ""
}

type GetLiveListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLiveListRequest) Reset() {
	*x = GetLiveListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLiveListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveListRequest) ProtoMessage() {}

func (x *GetLiveListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveListRequest.ProtoReflect.Descriptor instead.
func (*GetLiveListRequest) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{19}
}

type GetLiveListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LiveList []*Live `protobuf:"bytes,1,rep,name=LiveList,proto3" json:"LiveList,omitempty"`
	Code     string  `protobuf:"bytes,100,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg      string  `protobuf:"bytes,101,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *GetLiveListResponse) Reset() {
	*x = GetLiveListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLiveListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveListResponse) ProtoMessage() {}

func (x *GetLiveListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveListResponse.ProtoReflect.Descriptor instead.
func (*GetLiveListResponse) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{20}
}

func (x *GetLiveListResponse) GetLiveList() []*Live {
	if x != nil {
		return x.LiveList
	}
	return nil
}

func (x *GetLiveListResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetLiveListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateLiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Live *Live `protobuf:"bytes,1,opt,name=Live,proto3" json:"Live,omitempty"`
}

func (x *CreateLiveRequest) Reset() {
	*x = CreateLiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLiveRequest) ProtoMessage() {}

func (x *CreateLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLiveRequest.ProtoReflect.Descriptor instead.
func (*CreateLiveRequest) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{21}
}

func (x *CreateLiveRequest) GetLive() *Live {
	if x != nil {
		return x.Live
	}
	return nil
}

type CreateLiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Code string `protobuf:"bytes,100,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,101,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *CreateLiveResponse) Reset() {
	*x = CreateLiveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLiveResponse) ProtoMessage() {}

func (x *CreateLiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLiveResponse.ProtoReflect.Descriptor instead.
func (*CreateLiveResponse) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{22}
}

func (x *CreateLiveResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateLiveResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateLiveResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateLiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Live *Live `protobuf:"bytes,1,opt,name=Live,proto3" json:"Live,omitempty"`
}

func (x *UpdateLiveRequest) Reset() {
	*x = UpdateLiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLiveRequest) ProtoMessage() {}

func (x *UpdateLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLiveRequest.ProtoReflect.Descriptor instead.
func (*UpdateLiveRequest) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateLiveRequest) GetLive() *Live {
	if x != nil {
		return x.Live
	}
	return nil
}

type UpdateLiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,100,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,101,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *UpdateLiveResponse) Reset() {
	*x = UpdateLiveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLiveResponse) ProtoMessage() {}

func (x *UpdateLiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLiveResponse.ProtoReflect.Descriptor instead.
func (*UpdateLiveResponse) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateLiveResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateLiveResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteLiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLiveRequest) Reset() {
	*x = DeleteLiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLiveRequest) ProtoMessage() {}

func (x *DeleteLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLiveRequest.ProtoReflect.Descriptor instead.
func (*DeleteLiveRequest) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteLiveRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteLiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,100,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,101,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *DeleteLiveResponse) Reset() {
	*x = DeleteLiveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dormitoryService_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLiveResponse) ProtoMessage() {}

func (x *DeleteLiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dormitoryService_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLiveResponse.ProtoReflect.Descriptor instead.
func (*DeleteLiveResponse) Descriptor() ([]byte, []int) {
	return file_dormitoryService_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteLiveResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeleteLiveResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_dormitoryService_proto protoreflect.FileDescriptor

var file_dormitoryService_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xa1, 0x01, 0x0a,
	0x09, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x6c,
	0x6f, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x46, 0x6c, 0x6f, 0x6f, 0x72,
	0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x69, 0x76, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x4c, 0x69, 0x76, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x4d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x53, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x53, 0x6e,
	0x22, 0x29, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x53,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x53, 0x6e, 0x22, 0x75, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0d, 0x44, 0x6f, 0x72, 0x6d, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0d, 0x44,
	0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x22, 0x45, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x09,
	0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x09,
	0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x4f, 0x0a, 0x17, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x64, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x45, 0x0a, 0x16, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x72,
	0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x09, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x22, 0x3f, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x3f, 0x0a, 0x17,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x73, 0x67, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x5e, 0x0a,
	0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x6d, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x6d, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x71, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69,
	0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x0c, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x4d, 0x73, 0x67, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x41,
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e,
	0x67, 0x22, 0x4e, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73,
	0x67, 0x22, 0x41, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x69, 0x6e, 0x67, 0x22, 0x3e, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4d, 0x73, 0x67, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x3e, 0x0a,
	0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x73, 0x67, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x72, 0x0a,
	0x04, 0x4c, 0x69, 0x76, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x6f, 0x72, 0x6d,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x69, 0x76, 0x65, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x69, 0x76, 0x65, 0x44, 0x61, 0x74,
	0x65, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x61, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x08, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x08, 0x4c, 0x69, 0x76, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x64, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x31, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x04, 0x4c, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x04, 0x4c, 0x69, 0x76, 0x65, 0x22, 0x4a, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x65,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x31, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x04, 0x4c, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x04, 0x4c, 0x69, 0x76, 0x65, 0x22, 0x3a, 0x0a, 0x12,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x65, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x3a, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x65,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x32, 0xe3, 0x06, 0x0a, 0x10, 0x44, 0x6f,
	0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x72, 0x6d, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1a, 0x2e, 0x70,
	0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x6f, 0x72, 0x6d, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x76, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65,
	0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dormitoryService_proto_rawDescOnce sync.Once
	file_dormitoryService_proto_rawDescData = file_dormitoryService_proto_rawDesc
)

func file_dormitoryService_proto_rawDescGZIP() []byte {
	file_dormitoryService_proto_rawDescOnce.Do(func() {
		file_dormitoryService_proto_rawDescData = protoimpl.X.CompressGZIP(file_dormitoryService_proto_rawDescData)
	})
	return file_dormitoryService_proto_rawDescData
}

var file_dormitoryService_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_dormitoryService_proto_goTypes = []interface{}{
	(*Dormitory)(nil),                // 0: pb.Dormitory
	(*GetDormitoryListRequest)(nil),  // 1: pb.GetDormitoryListRequest
	(*GetDormitoryListResponse)(nil), // 2: pb.GetDormitoryListResponse
	(*CreateDormitoryRequest)(nil),   // 3: pb.CreateDormitoryRequest
	(*CreateDormitoryResponse)(nil),  // 4: pb.CreateDormitoryResponse
	(*UpdateDormitoryRequest)(nil),   // 5: pb.UpdateDormitoryRequest
	(*UpdateDormitoryResponse)(nil),  // 6: pb.UpdateDormitoryResponse
	(*DeleteDormitoryRequest)(nil),   // 7: pb.DeleteDormitoryRequest
	(*DeleteDormitoryResponse)(nil),  // 8: pb.DeleteDormitoryResponse
	(*Building)(nil),                 // 9: pb.Building
	(*GetBuildingListRequest)(nil),   // 10: pb.GetBuildingListRequest
	(*GetBuildingListResponse)(nil),  // 11: pb.GetBuildingListResponse
	(*CreateBuildingRequest)(nil),    // 12: pb.CreateBuildingRequest
	(*CreateBuildingResponse)(nil),   // 13: pb.CreateBuildingResponse
	(*UpdateBuildingRequest)(nil),    // 14: pb.UpdateBuildingRequest
	(*UpdateBuildingResponse)(nil),   // 15: pb.UpdateBuildingResponse
	(*DeleteBuildingRequest)(nil),    // 16: pb.DeleteBuildingRequest
	(*DeleteBuildingResponse)(nil),   // 17: pb.DeleteBuildingResponse
	(*Live)(nil),                     // 18: pb.Live
	(*GetLiveListRequest)(nil),       // 19: pb.GetLiveListRequest
	(*GetLiveListResponse)(nil),      // 20: pb.GetLiveListResponse
	(*CreateLiveRequest)(nil),        // 21: pb.CreateLiveRequest
	(*CreateLiveResponse)(nil),       // 22: pb.CreateLiveResponse
	(*UpdateLiveRequest)(nil),        // 23: pb.UpdateLiveRequest
	(*UpdateLiveResponse)(nil),       // 24: pb.UpdateLiveResponse
	(*DeleteLiveRequest)(nil),        // 25: pb.DeleteLiveRequest
	(*DeleteLiveResponse)(nil),       // 26: pb.DeleteLiveResponse
}
var file_dormitoryService_proto_depIdxs = []int32{
	0,  // 0: pb.GetDormitoryListResponse.DormitoryList:type_name -> pb.Dormitory
	0,  // 1: pb.CreateDormitoryRequest.Dormitory:type_name -> pb.Dormitory
	0,  // 2: pb.UpdateDormitoryRequest.Dormitory:type_name -> pb.Dormitory
	9,  // 3: pb.GetBuildingListResponse.BuildingList:type_name -> pb.Building
	9,  // 4: pb.CreateBuildingRequest.Building:type_name -> pb.Building
	9,  // 5: pb.UpdateBuildingRequest.Building:type_name -> pb.Building
	18, // 6: pb.GetLiveListResponse.LiveList:type_name -> pb.Live
	18, // 7: pb.CreateLiveRequest.Live:type_name -> pb.Live
	18, // 8: pb.UpdateLiveRequest.Live:type_name -> pb.Live
	1,  // 9: pb.DormitoryService.GetDormitoryList:input_type -> pb.GetDormitoryListRequest
	3,  // 10: pb.DormitoryService.CreateDormitory:input_type -> pb.CreateDormitoryRequest
	5,  // 11: pb.DormitoryService.UpdateDormitory:input_type -> pb.UpdateDormitoryRequest
	7,  // 12: pb.DormitoryService.DeleteDormitory:input_type -> pb.DeleteDormitoryRequest
	10, // 13: pb.DormitoryService.GetBuildingList:input_type -> pb.GetBuildingListRequest
	12, // 14: pb.DormitoryService.CreateBuilding:input_type -> pb.CreateBuildingRequest
	14, // 15: pb.DormitoryService.UpdateBuilding:input_type -> pb.UpdateBuildingRequest
	16, // 16: pb.DormitoryService.DeleteBuilding:input_type -> pb.DeleteBuildingRequest
	19, // 17: pb.DormitoryService.GetLiveList:input_type -> pb.GetLiveListRequest
	21, // 18: pb.DormitoryService.CreateLive:input_type -> pb.CreateLiveRequest
	23, // 19: pb.DormitoryService.UpdateLive:input_type -> pb.UpdateLiveRequest
	25, // 20: pb.DormitoryService.DeleteLive:input_type -> pb.DeleteLiveRequest
	2,  // 21: pb.DormitoryService.GetDormitoryList:output_type -> pb.GetDormitoryListResponse
	4,  // 22: pb.DormitoryService.CreateDormitory:output_type -> pb.CreateDormitoryResponse
	6,  // 23: pb.DormitoryService.UpdateDormitory:output_type -> pb.UpdateDormitoryResponse
	8,  // 24: pb.DormitoryService.DeleteDormitory:output_type -> pb.DeleteDormitoryResponse
	11, // 25: pb.DormitoryService.GetBuildingList:output_type -> pb.GetBuildingListResponse
	13, // 26: pb.DormitoryService.CreateBuilding:output_type -> pb.CreateBuildingResponse
	15, // 27: pb.DormitoryService.UpdateBuilding:output_type -> pb.UpdateBuildingResponse
	17, // 28: pb.DormitoryService.DeleteBuilding:output_type -> pb.DeleteBuildingResponse
	20, // 29: pb.DormitoryService.GetLiveList:output_type -> pb.GetLiveListResponse
	22, // 30: pb.DormitoryService.CreateLive:output_type -> pb.CreateLiveResponse
	24, // 31: pb.DormitoryService.UpdateLive:output_type -> pb.UpdateLiveResponse
	26, // 32: pb.DormitoryService.DeleteLive:output_type -> pb.DeleteLiveResponse
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_dormitoryService_proto_init() }
func file_dormitoryService_proto_init() {
	if File_dormitoryService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dormitoryService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dormitory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDormitoryListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDormitoryListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDormitoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDormitoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDormitoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDormitoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDormitoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDormitoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Building); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBuildingListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBuildingListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBuildingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBuildingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBuildingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBuildingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBuildingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBuildingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Live); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLiveListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLiveListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLiveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLiveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dormitoryService_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLiveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dormitoryService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dormitoryService_proto_goTypes,
		DependencyIndexes: file_dormitoryService_proto_depIdxs,
		MessageInfos:      file_dormitoryService_proto_msgTypes,
	}.Build()
	File_dormitoryService_proto = out.File
	file_dormitoryService_proto_rawDesc = nil
	file_dormitoryService_proto_goTypes = nil
	file_dormitoryService_proto_depIdxs = nil
}
